name: 'Scan Elasticsearch Docker Image'

on:
  workflow_dispatch:

jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Scan ubuntu/nginx:1.28-26.04_edge image with Trivy (Docker)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:0.69.1 \
            image \
            --severity CRITICAL,HIGH \
            --ignore-unfixed \
            ubuntu/nginx:1.28-26.04_edge
