name: 'Scan Elasticsearch Docker Image'

on:
  workflow_dispatch:

jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Scan Elasticsearch 9.3.6 image with Trivy
        uses: aquasecurity/trivy-action@v0.34.0
        with:
          image-ref: 'elastic/elasticsearch:9.3.6'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
        env:                          # 👈 添加这部分
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 👈 添加这部分
